// Committed catalog (metadata only) — generated by scripts/ingest-effects.ts and
// hand-curated. Asset bytes live on the persistent volume under STORAGE_ROOT/effects.
import catalogJson from "./catalog.json";
import type { EffectCategory, EffectEntry } from "./catalog-types";

export const EFFECTS_CATALOG: EffectEntry[] = catalogJson as EffectEntry[];

export function getEffect(presetId: string): EffectEntry | undefined {
  return EFFECTS_CATALOG.find((entry) => entry.presetId === presetId);
}

// Lightweight keyword search over name / description / useWhen / category, so the
// agent (via search_effects) and the store UI share one ranking.
export function searchEffects(query: string, category?: EffectCategory): EffectEntry[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  const pool = category
    ? EFFECTS_CATALOG.filter((entry) => entry.category === category)
    : EFFECTS_CATALOG;
  if (terms.length === 0) return pool;
  const scored = pool.map((entry) => {
    const haystack = [entry.name, entry.description, entry.category, ...entry.useWhen]
      .join(" ")
      .toLowerCase();
    let score = 0;
    for (const term of terms) {
      if (entry.useWhen.some((tag) => tag.toLowerCase() === term)) score += 3;
      else if (haystack.includes(term)) score += 1;
    }
    return { entry, score };
  });
  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((s) => s.entry);
}
